/* The following code was generated by JFlex 1.6.1 */

package analisador;

import static analisador.Token.*;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>/home/arantesandre97/Developer/trabalho-compiladores/Analisador/src/analisador/Lexer.flex</tt>
 */
class Lexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\5\1\7\1\46\1\46\1\45\22\0\1\6\1\20\1\42"+
    "\1\44\1\0\1\12\1\0\1\43\1\34\1\35\1\0\1\13\1\41"+
    "\1\14\1\4\1\11\12\2\1\0\1\40\1\22\1\23\1\21\1\24"+
    "\1\0\1\50\1\1\1\54\1\1\1\15\1\53\2\1\1\51\3\1"+
    "\1\47\1\52\1\16\1\1\1\60\1\57\1\56\1\55\1\17\2\1"+
    "\1\10\2\1\1\36\1\0\1\37\1\0\1\1\1\0\1\26\2\1"+
    "\1\33\1\1\1\25\5\1\1\27\2\1\1\31\3\1\1\30\2\1"+
    "\1\32\4\1\1\0\1\3\10\0\1\46\42\0\1\12\u1f7f\0\1\46"+
    "\1\46\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\1\2\4\1\5\2\6"+
    "\1\7\1\10\1\11\1\2\1\12\2\13\1\14\1\15"+
    "\2\2\1\16\1\17\1\20\1\21\1\22\1\23\1\24"+
    "\1\25\1\1\1\2\1\0\1\26\1\13\2\0\1\27"+
    "\4\0\2\2\1\0\1\30\1\2\1\31\13\0\1\2"+
    "\1\32\1\30\1\2\12\0\1\33\1\0\1\34\2\2"+
    "\4\0\1\35\1\0\1\36\1\37\1\40\3\0\1\2"+
    "\1\41\1\42\3\0\1\43\2\0\1\2\1\44\3\0"+
    "\1\45\1\46\1\0\1\47\4\0\1\50\1\51";

  private static int [] zzUnpackAction() {
    int [] result = new int[113];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\61\0\142\0\223\0\304\0\61\0\304\0\61"+
    "\0\142\0\61\0\61\0\304\0\142\0\365\0\61\0\u0126"+
    "\0\u0157\0\61\0\61\0\u0188\0\u01b9\0\61\0\61\0\61"+
    "\0\61\0\61\0\61\0\61\0\61\0\u01ea\0\u021b\0\u024c"+
    "\0\61\0\61\0\u027d\0\u02ae\0\61\0\u02df\0\u0310\0\u0341"+
    "\0\u0372\0\u03a3\0\u03d4\0\u0405\0\u0436\0\u0467\0\u024c\0\u0498"+
    "\0\u04c9\0\u04fa\0\u052b\0\u055c\0\u058d\0\u05be\0\u05ef\0\u0620"+
    "\0\u0651\0\u0682\0\u06b3\0\142\0\u0405\0\u06e4\0\u0715\0\u0746"+
    "\0\u0777\0\u07a8\0\u07d9\0\u080a\0\u083b\0\u086c\0\u089d\0\u08ce"+
    "\0\61\0\u08ff\0\61\0\u0930\0\u0961\0\u0992\0\u09c3\0\u09f4"+
    "\0\u0a25\0\61\0\u0a56\0\61\0\61\0\61\0\u0a87\0\u0ab8"+
    "\0\u0ae9\0\u0b1a\0\61\0\61\0\u0b4b\0\u0b7c\0\u0bad\0\61"+
    "\0\u0bde\0\u0c0f\0\u0c40\0\61\0\u0c71\0\u0ca2\0\u0cd3\0\61"+
    "\0\142\0\u0d04\0\61\0\u0d35\0\u0d66\0\u0d97\0\u0dc8\0\61"+
    "\0\61";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[113];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\2\1\6\1\7\1\10"+
    "\1\11\2\12\1\13\1\14\1\15\1\16\1\3\1\17"+
    "\1\20\1\21\1\22\1\23\1\24\4\3\1\25\1\3"+
    "\1\26\1\27\1\30\1\31\1\32\1\33\1\34\1\35"+
    "\1\36\1\6\1\0\10\3\1\37\1\3\62\0\2\3"+
    "\5\0\1\3\4\0\3\3\5\0\7\3\13\0\12\3"+
    "\2\0\1\4\1\0\1\40\56\0\1\4\57\0\2\3"+
    "\5\0\1\3\4\0\2\3\1\15\5\0\7\3\13\0"+
    "\12\3\21\0\1\41\1\0\1\42\46\0\1\43\3\0"+
    "\1\44\4\0\1\45\1\42\23\0\1\46\3\0\1\47"+
    "\2\0\1\50\1\51\2\0\2\3\5\0\1\3\4\0"+
    "\3\3\5\0\1\3\1\52\5\3\13\0\12\3\1\0"+
    "\2\3\5\0\1\3\4\0\3\3\5\0\6\3\1\53"+
    "\13\0\12\3\7\54\1\0\34\54\1\55\2\0\12\54"+
    "\1\0\2\3\5\0\1\3\4\0\1\56\2\3\5\0"+
    "\7\3\13\0\12\3\2\0\1\57\73\0\1\60\31\0"+
    "\1\61\3\0\1\62\2\0\1\63\1\64\53\0\1\65"+
    "\3\0\1\66\52\0\1\67\27\0\1\70\56\0\1\71"+
    "\120\0\1\72\4\0\2\3\5\0\1\3\4\0\3\3"+
    "\5\0\2\3\1\73\4\3\13\0\12\3\1\0\2\3"+
    "\5\0\1\3\4\0\3\3\5\0\6\3\1\74\13\0"+
    "\12\3\7\54\1\0\34\54\1\75\2\0\12\54\7\55"+
    "\1\0\35\55\2\0\12\55\1\0\2\3\5\0\1\3"+
    "\4\0\3\3\5\0\7\3\13\0\6\3\1\76\3\3"+
    "\52\0\1\77\3\0\1\100\52\0\1\101\27\0\1\102"+
    "\56\0\1\103\120\0\1\104\63\0\1\105\15\0\1\106"+
    "\114\0\1\107\61\0\1\110\27\0\1\111\30\0\1\112"+
    "\27\0\1\113\40\0\2\3\5\0\1\3\4\0\3\3"+
    "\5\0\3\3\1\114\3\3\13\0\12\3\1\0\2\3"+
    "\5\0\1\3\4\0\1\3\1\115\1\3\5\0\7\3"+
    "\13\0\12\3\60\0\1\116\15\0\1\117\114\0\1\120"+
    "\61\0\1\121\27\0\1\122\30\0\1\123\27\0\1\124"+
    "\60\0\1\125\60\0\1\126\111\0\1\127\62\0\1\130"+
    "\54\0\1\131\11\0\2\3\5\0\1\3\4\0\3\3"+
    "\5\0\4\3\1\74\2\3\13\0\12\3\1\0\2\3"+
    "\5\0\1\3\4\0\3\3\5\0\7\3\13\0\10\3"+
    "\1\132\1\3\21\0\1\133\60\0\1\134\111\0\1\135"+
    "\62\0\1\136\54\0\1\137\31\0\1\140\114\0\1\141"+
    "\21\0\1\142\43\0\2\3\5\0\1\3\4\0\3\3"+
    "\5\0\7\3\13\0\3\3\1\143\6\3\21\0\1\144"+
    "\114\0\1\145\21\0\1\146\113\0\1\147\30\0\1\150"+
    "\40\0\2\3\5\0\1\3\4\0\3\3\5\0\7\3"+
    "\13\0\1\3\1\151\10\3\51\0\1\152\30\0\1\153"+
    "\55\0\1\154\60\0\1\155\114\0\1\156\60\0\1\157"+
    "\27\0\1\160\60\0\1\161\37\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[3577];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\3\1\1\11\1\1\1\11\1\1\2\11"+
    "\3\1\1\11\2\1\2\11\2\1\10\11\2\1\1\0"+
    "\2\11\2\0\1\11\4\0\2\1\1\0\3\1\13\0"+
    "\4\1\12\0\1\11\1\0\1\11\2\1\4\0\1\11"+
    "\1\0\3\11\3\0\1\1\2\11\3\0\1\11\2\0"+
    "\1\1\1\11\3\0\1\11\1\1\1\0\1\11\4\0"+
    "\2\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[113];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
public String lexeme;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 196) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Token yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { return ERROR;
            }
          case 42: break;
          case 2: 
            { lexeme=yytext(); return IDENTIFICADOR;
            }
          case 43: break;
          case 3: 
            { lexeme=yytext(); return INTEIRO;
            }
          case 44: break;
          case 4: 
            { /*Ignore*/
            }
          case 45: break;
          case 5: 
            { lexeme = yytext(); return LINHA;
            }
          case 46: break;
          case 6: 
            { lexeme = yytext(); return OP_ARITMETICO;
            }
          case 47: break;
          case 7: 
            { lexeme = yytext(); return OP_SOMA;
            }
          case 48: break;
          case 8: 
            { lexeme = yytext(); return OP_SUBTRACAO;
            }
          case 49: break;
          case 9: 
            { lexeme = yytext(); return OP_LOGICO;
            }
          case 50: break;
          case 10: 
            { lexeme = yytext(); return OP_NEGACAO;
            }
          case 51: break;
          case 11: 
            { lexeme = yytext(); return OP_RELACIONAL;
            }
          case 52: break;
          case 12: 
            { lexeme = yytext(); return OP_IGUAL;
            }
          case 53: break;
          case 13: 
            { lexeme = yytext(); return OP_DIFERENTE;
            }
          case 54: break;
          case 14: 
            { lexeme = yytext(); return ABRE_PARENTESES;
            }
          case 55: break;
          case 15: 
            { lexeme = yytext(); return FECHA_PARENTESES;
            }
          case 56: break;
          case 16: 
            { lexeme = yytext(); return ABRE_COLCHETES;
            }
          case 57: break;
          case 17: 
            { lexeme = yytext(); return FECHA_COLCHETES;
            }
          case 58: break;
          case 18: 
            { lexeme = yytext(); return PONTO_VIRGULA;
            }
          case 59: break;
          case 19: 
            { lexeme = yytext(); return VIRGULA;
            }
          case 60: break;
          case 20: 
            { lexeme = yytext(); return ASPAS_DUPLAS;
            }
          case 61: break;
          case 21: 
            { lexeme = yytext(); return ASPAS_SIMPLES;
            }
          case 62: break;
          case 22: 
            { lexeme = yytext(); return LEIA;
            }
          case 63: break;
          case 23: 
            { lexeme = yytext(); return ESCREVA;
            }
          case 64: break;
          case 24: 
            { lexeme = yytext(); return COMENTARIO;
            }
          case 65: break;
          case 25: 
            { lexeme=yytext(); return REAL;
            }
          case 66: break;
          case 26: 
            { lexeme=yytext(); return OP_BOOLEANO;
            }
          case 67: break;
          case 27: 
            { lexeme = yytext(); return SE;
            }
          case 68: break;
          case 28: 
            { lexeme = yytext(); return REPETICAO;
            }
          case 69: break;
          case 29: 
            { lexeme = yytext(); return SE_FIM;
            }
          case 70: break;
          case 30: 
            { lexeme = yytext(); return REPETICAO_FIM;
            }
          case 71: break;
          case 31: 
            { lexeme = yytext(); return ENQUANTO;
            }
          case 72: break;
          case 32: 
            { lexeme = yytext(); return ESE;
            }
          case 73: break;
          case 33: 
            { lexeme = yytext(); return ENQUANTO_FIM;
            }
          case 74: break;
          case 34: 
            { lexeme = yytext(); return ESE_FIM;
            }
          case 75: break;
          case 35: 
            { lexeme = yytext(); return PRINCIPAL;
            }
          case 76: break;
          case 36: 
            { lexeme = yytext(); return FIM;
            }
          case 77: break;
          case 37: 
            { lexeme = yytext(); return SENAO;
            }
          case 78: break;
          case 38: 
            { lexeme = yytext(); return RETORNA;
            }
          case 79: break;
          case 39: 
            { lexeme = yytext(); return SENAO_FIM;
            }
          case 80: break;
          case 40: 
            { lexeme = yytext(); return FUNCAO;
            }
          case 81: break;
          case 41: 
            { lexeme = yytext(); return FUNCAO_FIM;
            }
          case 82: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
