
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Oct 27 17:11:03 BRT 2019
//----------------------------------------------------

package analisador;

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int FECHA_COLCHETES = 14;
  public static final int FUNCAO = 22;
  public static final int ASPAS_DUPLAS = 17;
  public static final int SENAO_FIM = 29;
  public static final int OP_NEGACAO = 6;
  public static final int SE = 24;
  public static final int OP_SUBTRACAO = 4;
  public static final int FUNCAO_FIM = 23;
  public static final int ESE = 26;
  public static final int SE_FIM = 25;
  public static final int FIM = 21;
  public static final int VIRGULA = 16;
  public static final int PRINCIPAL = 20;
  public static final int IDENTIFICADOR = 37;
  public static final int REPETICAO = 30;
  public static final int ESE_FIM = 27;
  public static final int OP_BOOLEANO = 10;
  public static final int OP_DIFERENTE = 9;
  public static final int OP_RELACIONAL = 7;
  public static final int EOF = 0;
  public static final int OP_ARITMETICO = 2;
  public static final int PONTO_VIRGULA = 15;
  public static final int ABRE_PARENTESES = 11;
  public static final int error = 1;
  public static final int SENAO = 28;
  public static final int ENQUANTO = 32;
  public static final int ENQUANTO_FIM = 33;
  public static final int COMENTARIO = 19;
  public static final int ESCREVA = 34;
  public static final int OP_SOMA = 3;
  public static final int RETORNA = 36;
  public static final int ERROR = 40;
  public static final int REAL = 39;
  public static final int LEIA = 35;
  public static final int ABRE_COLCHETES = 13;
  public static final int OP_IGUAL = 8;
  public static final int INTEIRO = 38;
  public static final int OP_LOGICO = 5;
  public static final int REPETICAO_FIM = 31;
  public static final int FECHA_PARENTESES = 12;
  public static final int ASPAS_SIMPLES = 18;
}

