
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Oct 28 20:51:26 BRT 2019
//----------------------------------------------------

package analisador;

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int FECHA_COLCHETES = 17;
  public static final int FUNCAO = 23;
  public static final int SENAO_FIM = 30;
  public static final int OP_NEGACAO = 9;
  public static final int SE = 25;
  public static final int OP_SUBTRACAO = 3;
  public static final int FUNCAO_FIM = 24;
  public static final int ESE = 27;
  public static final int SE_FIM = 26;
  public static final int FIM = 22;
  public static final int VIRGULA = 19;
  public static final int PRINCIPAL = 21;
  public static final int IDENTIFICADOR = 38;
  public static final int OP_MULTIPLICACAO = 4;
  public static final int REPETICAO = 31;
  public static final int ESE_FIM = 28;
  public static final int OP_BOOLEANO = 13;
  public static final int OP_DIFERENTE = 12;
  public static final int OP_MOD = 7;
  public static final int OP_RELACIONAL = 10;
  public static final int EOF = 0;
  public static final int PONTO_VIRGULA = 18;
  public static final int ABRE_PARENTESES = 14;
  public static final int error = 1;
  public static final int OP_DIVISAO = 5;
  public static final int SENAO = 29;
  public static final int ENQUANTO = 33;
  public static final int ENQUANTO_FIM = 34;
  public static final int OP_EXPONENCIACAO = 6;
  public static final int COMENTARIO = 20;
  public static final int ESCREVA = 35;
  public static final int OP_SOMA = 2;
  public static final int RETORNA = 37;
  public static final int REAL = 41;
  public static final int LEIA = 36;
  public static final int ABRE_COLCHETES = 16;
  public static final int OP_IGUAL = 11;
  public static final int INTEIRO = 40;
  public static final int OP_LOGICO = 8;
  public static final int REPETICAO_FIM = 32;
  public static final int FECHA_PARENTESES = 15;
  public static final int STRING = 39;
}

