package analisador;


public enum Token {
    LINHA, OP_ARITMETICO, OPERADOR_LOGICO, OP_RELACIONAL, OP_COMPARACAO, OP_BOOLEANO,
    ABRE_PARENTESES, FECHA_PARENTESES, ABRE_COLCHETES, FECHA_COLCHETES,
    PONTO_VIRGULA, DOIS_PONTOS, VIRGULA, PONTO, ASPAS_DUPLAS, ASPAS_SIMPLES,  
    COMENTARIO, PRINCIPAL, FIM, FUNCAO, FUNCAO_FIM, SE, SE_FIM, ESE, ESE_FIM, 
    SENAO, SENAO_FIM, REPETICAO, REPETICAO_FIM, ENQUANTO, ENQUANTO_FIM, ESCREVA, 
    LEIA, RETORNA, IDENTIFICADOR, INTEIRO, REAL, ERROR
}
