package analisador;


public enum Token {
    LINHA, OP_ARITMETICO, OPERADOR_LOGICO, OP_RELACIONAL, OP_BOOLEANO,
    SEPARADOR, COMENTARIO, PRINCIPAL, FIM, FUNCAO, FUNCAO_FIM, SE,
    SE_FIM, ESE, ESE_FIM, SENAO, SENAO_FIM, REPETICAO, REPETICAO_FIM,
    ENQUANTO, ENQUANTO_FIM, ESCREVA, LEIA, RETORNA, ERROR, PALAVRA,
    NUMERO,
}
