package analisador;


public enum Token {
    LINHA, OP_ARITMETICO, OP_SOMA, OP_SUBTRACAO, OP_LOGICO, OP_NEGACAO,
    OP_RELACIONAL, OP_IGUAL, OP_DIFERENTE, OP_BOOLEANO, ABRE_PARENTESES, 
    FECHA_PARENTESES, ABRE_COLCHETES, FECHA_COLCHETES, PONTO_VIRGULA, 
    VIRGULA, ASPAS_DUPLAS, ASPAS_SIMPLES, COMENTARIO, PRINCIPAL, FIM, FUNCAO, 
    FUNCAO_FIM, SE, SE_FIM, ESE, ESE_FIM, SENAO, SENAO_FIM, REPETICAO, REPETICAO_FIM, 
    ENQUANTO, ENQUANTO_FIM, ESCREVA, LEIA, RETORNA, IDENTIFICADOR, INTEIRO, REAL, ERROR
}
